apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-secret
  namespace: ecom-app
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/part-of: ecom-app
type: Opaque
stringData:
  MYSQL_DSN: "catalog-user:rootp@55word@tcp(192.168.68.160:3306)/catalog-db?parseTime=true&multiStatements=true"
  MYSQL_HOST: "mysql.ecom-app.svc.cluster.local"
  MYSQL_PORT: "3306"
  MYSQL_USER: "catalog-user"
  MYSQL_PASSWORD: "rootp@55word"
  MYSQL_DATABASE: "catalog-db"
  REDIS_PASSWORD: "Str0ngP@ssw0rd"
  ADMIN_TOKEN: "chang3Me@dm!nT0ken"